version: "3.8"

services:
  postgres:
    image: postgres:15
    env_file:
      - .env
    ports:
      - "5433:5432"  
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    env_file:
      - .env
    depends_on:
      - postgres

volumes:
  postgres_data:
